/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cam_CamTestLib_GlTexture */

#ifndef _Included_com_example_cam_CamTestLib_GlTexture
#define _Included_com_example_cam_CamTestLib_GlTexture
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
